redmine_warehouse/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :products
get 'projects/:project_id/products', :to => 'products#index', :as => 'project_products'
get 'projects/:project_id/products/new', :to => 'products#new', :as => 'new_project_product'
get 'projects/:project_id/products/:id', :to => 'products#show', :as => 'project_product'
get 'projects/:project_id/products/:id/edit', :to => 'products#edit', :as => 'edit_project_product'
post 'projects/:project_id/products', :to => 'products#create'

redmine_warehouse/app/models/redmine_warehouse_product.rb
class RedmineWarehouseProduct < ActiveRecord::Base
	belongs_to :issue
	validates_presence_of :name, :message => ' товара не может быть пустым'
  validates_uniqueness_of :name, :message => 'товара не может повторяться'
  
	def self.safe_attributes(*args)
        @safe_attributes ||= []
        if args.empty?
          if superclass.include?(Redmine::SafeAttributes)
            @safe_attributes + superclass.safe_attributes 
          else
            @safe_attributes
          end
        else
          options = args.last.is_a?(Hash) ? args.pop : {}
          @safe_attributes << [args, options]
        end
      end
  end

redmine_warehouse/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  default_search_scope :products
  helper ProductsHelper
  include QueriesHelper
  before_action :authorize, :only => [:new] 
  before_action :find_project, :authorize
  before_action :find_product,:authorize, :only => [:show, :edit, :update, :destroy]
  before_action :build_new_product_from_params, :only => [ :edit]
  
  def index  	
  	@products = RedmineWarehouseProduct.all    
  end

  def show 
      
  end

 def new    
    @product = RedmineWarehouseProduct.new
    build_new_product_from_params 
    respond_to do |format|
      format.html { render :action => 'new', :layout => !request.xhr?}
      format.js
    end
  end

  def create
    @product = RedmineWarehouseProduct.new
    build_new_product_from_params 
    if @product.save
      redirect_to project_product_path(id: @product.id, project_id: params[:project_id])
      respond_to do |format|
        format.html {
          flash[:notice] = l(:notice_product_successful_create, :name => view_context.link_to("#{@product.name}", project_product_path(id: @product.id, project_id: params[:project_id]), :title => @product.name))
        }
        
      end
      return
    else
      respond_to do |format|
        format.html {
          if @product.nil?
            render_error :status => 422
          else
            render :action => 'new'
          end
        }
        
      end
    end
  end

  def edit

  end

  def update
    @product = RedmineWarehouseProduct.find(params[:id]) 
    build_new_product_from_params   
    
    if @product.save         
      flash[:notice] = l(:notice_product_successful_update, :name => view_context.link_to("#{@product.name}", project_product_path(id: @product.id, project_id: params[:project_id]), :title => @product.name))
      redirect_to project_product_path(id: @product.id, project_id: params[:project_id])
    else
      render :action => 'edit'
    end
  end

  def destroy 
    puts 'PRODUCT_ID'
    puts @product.id    
    if @product.destroy
      flash[:notice] = l(:notice_product_successful_destroy)
    end
    puts 'DESTROYED'
    redirect_to project_products_path(params[:project_id])
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def build_new_product_from_params

    @issues = @project.issues    
    @attrs = (params[:redmine_warehouse_product] || {}).deep_dup
    if @attrs.present?
      @product.name = @attrs[:name]
      @product.quantity = @attrs[:quantity]
      @product.cost = @attrs[:cost]
      @product.manufacture_date = @attrs[:manufacture_date]
      @product.issue_id = @attrs[:issue_id]
    end
  end

  # Redirects user after a successful product creation
  def redirect_after_create
    redirect_to project_products_path(params[:project_id])    
  end

 

  def find_product
    @product = RedmineWarehouseProduct.find(params[:id])   
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

redmine_warehouse/app/helpers/products_helper.rb
module ProductsHelper
	def render_half_width_custom_fields_rows(issue)
	    values = issue.visible_custom_field_values.reject {|value| value.custom_field.full_width_layout?}
	    return if values.empty?
	    half = (values.size / 2.0).ceil
	    issue_fields_rows do |rows|
	      values.each_with_index do |value, i|
	        css = "cf_#{value.custom_field.id}"
	        attr_value = show_value(value)
	        if value.custom_field.text_formatting == 'full'
	          attr_value = content_tag('div', attr_value, class: 'wiki')
	        end
	        m = (i < half ? :left : :right)
	        rows.send m, custom_field_name_tag(value.custom_field), attr_value, :class => css
	      end
	    end
	  end
end

redmine_warehouse/app/views/products/_action_menu.html.erb
<div class="contextual">
<%= link_to l(:button_edit), edit_project_product_path(id: @product, project_id: params[:project_id]), :onclick => 'showAndScrollTo("update", "product_notes"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit)  %>

<%= link_to l(:button_delete), product_path(id: @product, project_id: params[:project_id]), :method => :delete, :data => {:confirm => l(:product_destroy_confirmation, :name => "#{@product.name}")}, :class => 'icon icon-del'  %>

<%= link_to l(:button_to_list), project_products_path(params[:project_id]), :class => 'icon icon-list'  %>
<%= link_to l(:label_product_new),new_project_product_path(@project), :class => 'icon icon-add new-issue' %>
</div>

redmine_warehouse/app/views/products/_form.html.erb
<p><%= f.text_field :name, :required => true, :size => 60, :label => l(:label_product_name) %></p>
<p><%= f.text_field :quantity, :cols => 60, :rows => 2,  :label => l(:label_product_quantity) %></p>
<p><%= f.text_field :cost, :cols => 60, :rows => 2, :label => l(:label_product_cost) %></p>
<p><%= f.date_field :manufacture_date, :cols => 60, :rows => 2, :label => l(:label_product_man_date) %></p>
<p><%= f.select(:issue_id, @issues.collect{|i| [i.subject, i.id]}, {:include_blank => true}, {:selected => params[:issue_id]})%></p>

redmine_warehouse/app/views/products/_issue_overview.html.erb
<% if RedmineWarehouseProduct.where(issue_id: issue.id).present? %>    
  <% links = [] %>
  <% RedmineWarehouseProduct.where(issue_id: issue.id).each do |product| %>
   	<% links << link_to(product.name, project_product_path(id: product.id, project_id: issue.project_id)) %>
  <% end %>
  
  <%= issue_fields_rows do |rows|
  rows.left l(:field_issue_list_product), safe_join(links, ', ')
  end %>
<% end %>

redmine_warehouse/app/views/products/_list.html.erb
<% if @products.present? %>
  <div class="autoscroll">
  <table class="list issue-report">    
    <thead>
      <tr>        
        <th> <%= l(:label_product_new) %> </th>
        <th> <%= l(:label_product_quantity) %> </th>
        <th> <%= l(:label_product_cost) %>  </th>
        <th> <%= l(:label_product_man_date) %>  </th>
        <th> <%= l(:label_product_issue_name) %>  </th>
        <th></th>
      </tr>
    </thead>    
    <tbody>
      <% @products.each_with_index do |product, index| %>
  	    <tr>  	      
  	      <td> <%= link_to product.name, project_product_path(id: product.id, project_id: params[:project_id]) %> </td>
  	      <td> <%= product.quantity %> </td>
  	      <td> <%= product.cost %> </td>
  	      <td> <%= product.manufacture_date.present? ? product.manufacture_date.strftime('%d.%m.%Y') : 'не указана' %> </td>
  	      <td> <%= link_to product.issue.subject, issue_path(product.issue_id) if product.issue_id.present?%> </td>
          <td> <%= link_to l(:button_edit), edit_project_product_path(id: product.id,project_id: params[:project_id]), :onclick => 'showAndScrollTo("update", "product_notes"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit) %></td>
  	    </tr>	
      <% end %>
    </tbody>
  </table>
  </div>

<% end %>    

redmine_warehouse/app/views/products/edit.html.erb
<div class="contextual">
  <%= link_to l(:button_to_list), project_products_path(params[:project_id])  %>
</div>
<%= title l(:label_product_edit) %>

<%= labelled_form_for @product, :url => product_path,
                             :html => {:id => 'product-form', :method => :put} do |f| %>
  <%= error_messages_for 'product' %>
 
  <div class="box tabular">
    <div id="all_attributes">
    <%=hidden_field_tag :project_id, params[:project_id] %>
    <%= render :partial => 'products/form', :locals => {:f => f} %>
    </div>

    
  </div>

  <%= submit_tag l(:button_edit) %>
  
<% end %>

<% content_for :header_tags do %>
    <%= robot_exclusion_tag %>
<% end %>

redmine_warehouse/app/views/products/index.html.erb
<div class="contextual">
 <%= link_to l(:label_product_new),new_project_product_path(@project), :class => 'icon icon-add new-issue' %>
 </div>
 <h2><%=l(:project_module_products)%></h2>

<p><%= render :partial => 'list', :locals => {:products => @products} %></p>

redmine_warehouse/app/views/products/new.html.erb
<div class="contextual">
  <%= link_to l(:button_to_list), project_products_path(params[:project_id])  %>
</div>
<%= title l(:label_product_new) %>

<%= labelled_form_for @product, :url => project_products_path(@project),
                             :html => {:id => 'product-form'} do |f| %>
  <%= error_messages_for 'product' %>
 
  <div class="box tabular">
    <div id="all_attributes">
    <%= render :partial => 'products/form', :locals => {:f => f} %>
    </div>

    
  </div>

  <%= submit_tag l(:button_create) %>
  
<% end %>

<% content_for :header_tags do %>
    <%= robot_exclusion_tag %>
<% end %>

redmine_warehouse/app/views/products/show.html.erb
<%= render :partial => 'action_menu' %>
<h2><%= @product.name %></h2>
<div class="box tabular">
<table>
	<% unless @product.quantity.blank? %>
		<tr>
			<td><b><%= l(:label_product_quantity) %></b>:</td>
			<td><%= @product.quantity %></td>
		</tr>
	<% end %>
	<% unless @product.cost.blank? %>
		<tr>
			<td><b><%= l(:label_product_cost) %></b>:</td>
			<td><%= @product.cost %></td>
		</tr>
	<% end %>
	<% unless @product.manufacture_date.blank? %>
		<tr>
			<td><b><%= l(:label_product_man_date) %></b>:</td>
			<td><%= @product.manufacture_date.strftime('%d.%m.%Y') %></td>
		</tr>
	<% end %>
	<% unless @product.issue_id.blank? %>
		<tr>
			<td><b><%= l(:label_product_issue_name) %></b>:</td>
			<td><%= link_to @product.issue.subject, issue_path(@product.issue_id) %></td>
		</tr>
	<% end %>
</table>
</div>